"""Shared model mixins and column helpers."""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import Date, DateTime, Numeric, String, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base

__all__ = [
    "Base",
    "UUIDMixin",
    "TimestampMixin",
    "CreatedAtMixin",
    "money",
    "fk_uuid",
    "short_code",
]


class UUIDMixin:
    """UUID primary key generated by PostgreSQL (``gen_random_uuid()``, PG13+)."""

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )


class CreatedAtMixin:
    """Append-only records — created, never modified."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class TimestampMixin(CreatedAtMixin):
    """Mutable records — tracked on both create and update."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


def money(*, nullable: bool = False, default: str | None = "0.00") -> Mapped[Decimal]:
    """NUMERIC(12,2) — exact decimal. Never float for currency."""
    return mapped_column(
        Numeric(12, 2),
        nullable=nullable,
        server_default=text(f"'{default}'") if default is not None else None,
    )


def percentage(*, nullable: bool = True) -> Mapped[Decimal | None]:
    """NUMERIC(5,2) — 0.00 to 100.00."""
    return mapped_column(Numeric(5, 2), nullable=nullable)


def fk_uuid(nullable: bool = False) -> Mapped[uuid.UUID]:
    """Plain UUID column for foreign keys (the FK itself is declared inline)."""
    return mapped_column(PGUUID(as_uuid=True), nullable=nullable)


def short_code(length: int = 32) -> Mapped[str]:
    """Human-readable business code such as ``PT-10248``."""
    return mapped_column(String(length), nullable=False, unique=True, index=True)


def day(*, nullable: bool = False) -> Mapped[date]:
    return mapped_column(Date, nullable=nullable)
