import {
  Activity,
  AlertTriangle,
  BadgeIndianRupee,
  Banknote,
  BarChart3,
  BedDouble,
  Bell,
  Boxes,
  Building2,
  CalendarDays,
  CalendarPlus,
  ClipboardList,
  Contact,
  CreditCard,
  Dumbbell,
  FileBarChart,
  FileText,
  FlaskConical,
  HeartPulse,
  LayoutDashboard,
  ListChecks,
  type LucideIcon,
  Pill,
  Receipt,
  ScrollText,
  Settings,
  Sparkles,
  ShieldCheck,
  ShoppingCart,
  Stethoscope,
  TrendingUp,
  UserPlus,
  Users,
  Wallet,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  ai: Sparkles,
  alert: AlertTriangle,
  analytics: BarChart3,
  appointments: CalendarDays,
  audit: ScrollText,
  bed: BedDouble,
  bell: Bell,
  billing: Receipt,
  branches: Building2,
  cart: ShoppingCart,
  consultation: Stethoscope,
  contacts: Contact,
  dashboard: LayoutDashboard,
  documents: FileText,
  expenses: Wallet,
  inventory: Boxes,
  labs: FlaskConical,
  payments: CreditCard,
  patients: Users,
  pnl: BadgeIndianRupee,
  prescriptions: Pill,
  progress: TrendingUp,
  rehab: Dumbbell,
  register: UserPlus,
  reports: FileBarChart,
  revenue: Banknote,
  schedule: CalendarPlus,
  security: ShieldCheck,
  settings: Settings,
  tasks: ListChecks,
  therapy: HeartPulse,
  worklist: ClipboardList,
}

export function icon(name: string): LucideIcon {
  return ICONS[name] ?? LayoutDashboard
}
