import * as React from 'react'
import { useNavigate } from 'react-router-dom'
import { CalendarPlus } from 'lucide-react'
import type { Appointment, AppointmentType } from '@/types'
import { PageHeader } from '@/components/layout/PageHeader'
import { SectionCard, StatTile } from '@/components/dashboard/SectionCard'
import { DataTable, type Column } from '@/components/ui/data-table'
import { AppointmentTimeline } from '@/components/appointments/AppointmentTimeline'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Field } from '@/components/ui/label'
import { StatusBadge } from '@/components/ui/status'
import { InitialsAvatar } from '@/components/ui/misc'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { useToast } from '@/components/ui/toast'
import { ErrorState, LoadingState } from '@/components/ui/query-state'
import { useQuery } from '@/hooks/useApi'
import { listClinicians } from '@/services/userService'
import { createAppointment, listAppointments, todayIso } from '@/services/appointmentService'
import { listPatients } from '@/services/patientService'
// The staff directory is still mock-backed — the Users module lands in a later
// step. Only the USR code is sent; the backend resolves and validates it.
import { useAuth } from '@/context/AuthContext'
import { formatDate, to12Hour } from '@/lib/utils'

const APPOINTMENT_TYPES: AppointmentType[] = [
  'New Consultation',
  'Follow-up',
  'Therapy Review',
  'Post-op Review',
  'Assessment',
]

export default function AppointmentsPage() {
  const navigate = useNavigate()
  const toast = useToast()
  const { has } = useAuth()
  const today = React.useMemo(() => todayIso(), [])

  const [bookOpen, setBookOpen] = React.useState(false)
  const [booking, setBooking] = React.useState(false)
  const [draft, setDraft] = React.useState({
    patientId: '',
    doctorId: '',
    type: 'Follow-up' as AppointmentType,
    date: today,
    time: '10:00',
  })

  // The whole diary — this page is the cross-department view.
  const { data, loading, error, refetch } = useQuery(
    () => listAppointments({ scope: 'branch', limit: 200 }),
    [],
  )
  const appointments = React.useMemo(
    () =>
      [...(data?.items ?? [])].sort(
        (a, b) => a.date.localeCompare(b.date) || a.time.localeCompare(b.time),
      ),
    [data],
  )

  // Only loaded once the booking dialog is opened.
  const { data: patientPage } = useQuery(() => listPatients({ limit: 100, sort: 'name' }), [], {
    enabled: bookOpen,
  })
  const patients = patientPage?.items ?? []

  // Active clinicians from the API, so a suspended or departed doctor
  // cannot still be booked.
  const { data: clinicians } = useQuery(() => listClinicians('doctor'), [])
  const doctors = clinicians ?? []
  const todaysList = appointments.filter((a) => a.date === today)
  const upcoming = appointments.filter((a) => a.date > today)

  async function book(e: React.FormEvent) {
    e.preventDefault()
    if (!draft.patientId || !draft.doctorId) {
      toast.error('Incomplete booking', 'Select both a patient and a doctor.')
      return
    }

    setBooking(true)
    try {
      // The appointment number and the queue token are both generated by the
      // backend — nothing about the identity of the booking is decided here.
      const created = await createAppointment({
        patientId: draft.patientId,
        doctorId: draft.doctorId,
        date: draft.date,
        time: draft.time,
        type: draft.type,
      })
      setBookOpen(false)
      refetch()
      toast.success(
        'Appointment booked',
        `${created.patientName} with ${created.doctor} on ${formatDate(created.date)} at ${to12Hour(created.time)} · token ${created.tokenNumber}.`,
      )
    } catch (err) {
      toast.error(
        'Could not book that slot',
        err instanceof Error ? err.message : 'Please try a different time.',
      )
    } finally {
      setBooking(false)
    }
  }

  const columns: Column<Appointment>[] = [
    {
      key: 'slot',
      header: 'Slot',
      cell: (row) => (
        <div>
          <p className="num font-medium">{to12Hour(row.time)}</p>
          <p className="text-[11.5px] text-muted-foreground">{formatDate(row.date)}</p>
        </div>
      ),
      sortValue: (row) => `${row.date}${row.time}`,
    },
    {
      key: 'patient',
      header: 'Patient',
      primary: true,
      cell: (row) => (
        <div className="flex items-center gap-2.5">
          {row.patientInitials && (
            <InitialsAvatar
              initials={row.patientInitials}
              color={row.patientAvatarColor ?? ''}
              className="size-8"
            />
          )}
          <div className="min-w-0">
            <p className="truncate font-medium">{row.patientName}</p>
            <p className="num truncate text-[11.5px] text-muted-foreground">
              {row.patientId} · {row.patientAge} yrs
            </p>
          </div>
        </div>
      ),
      sortValue: (row) => row.patientName,
    },
    { key: 'doctor', header: 'Doctor', cell: (row) => row.doctor, sortValue: (row) => row.doctor },
    { key: 'type', header: 'Type', cell: (row) => row.type, sortValue: (row) => row.type },
    { key: 'department', header: 'Department', cell: (row) => row.department, sortValue: (row) => row.department },
    {
      key: 'checkin',
      header: 'Check-in',
      cell: (row) =>
        row.checkedInAt ? (
          <span className="num text-[12.5px] text-success">{to12Hour(row.checkedInAt)}</span>
        ) : (
          <span className="text-[12.5px] text-muted-foreground">—</span>
        ),
    },
    { key: 'status', header: 'Status', meta: true, cell: (row) => <StatusBadge status={row.status} /> },
  ]

  /** Every tab renders the same table; only the rows differ. */
  function Diary({ rows, emptyTitle, emptyDescription }: { rows: Appointment[]; emptyTitle?: string; emptyDescription?: string }) {
    if (loading) return <LoadingState label="Loading the diary" className="border-0 shadow-none" />
    if (error)
      return (
        <ErrorState
          title="Could not load appointments"
          message={error}
          onRetry={refetch}
          className="border-0 shadow-none"
        />
      )
    return (
      <DataTable
        columns={columns}
        rows={rows}
        rowKey={(row) => row.id}
        onRowClick={(row) => navigate(`/patients/${row.patientId}`)}
        initialSort={{ key: 'slot', dir: 'asc' }}
        emptyTitle={emptyTitle}
        emptyDescription={emptyDescription}
      />
    )
  }

  return (
    <>
      <PageHeader
        title="Appointments"
        description="The full booking diary across every doctor and department."
        crumbs={[{ label: 'Appointments' }]}
        actions={
          has('appointment.create') && (
            <Button onClick={() => setBookOpen(true)}>
              <CalendarPlus />
              Book appointment
            </Button>
          )
        }
      />

      <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatTile label="Today" value={loading ? '—' : todaysList.length} />
        <StatTile
          label="Waiting"
          value={loading ? '—' : todaysList.filter((a) => a.status === 'Waiting').length}
          tone="warning"
        />
        <StatTile
          label="Completed"
          value={loading ? '—' : todaysList.filter((a) => a.status === 'Completed').length}
          tone="success"
        />
        <StatTile label="Upcoming" value={loading ? '—' : upcoming.length} tone="info" />
      </div>

      <Tabs defaultValue="today">
        <TabsList>
          <TabsTrigger value="today">Today ({todaysList.length})</TabsTrigger>
          <TabsTrigger value="upcoming">Upcoming ({upcoming.length})</TabsTrigger>
          <TabsTrigger value="all">All ({appointments.length})</TabsTrigger>
        </TabsList>

        <TabsContent value="today">
          <div className="grid gap-5 xl:grid-cols-3">
            <SectionCard title="Today's diary" description={formatDate(today)} className="xl:col-span-2">
              <Diary
                rows={todaysList}
                emptyTitle="Nothing booked today"
                emptyDescription="Bookings made at the front desk appear here."
              />
            </SectionCard>

            <SectionCard title="Timeline" description="Chronological view of today." delay={0.05}>
              {loading ? (
                <LoadingState label="Loading" className="border-0 shadow-none" />
              ) : (
                <AppointmentTimeline appointments={todaysList} showDoctor />
              )}
            </SectionCard>
          </div>
        </TabsContent>

        <TabsContent value="upcoming">
          <SectionCard title="Upcoming" description="Everything booked beyond today.">
            <Diary
              rows={upcoming}
              emptyTitle="Nothing booked yet"
              emptyDescription="Use “Book appointment” to add a future slot."
            />
          </SectionCard>
        </TabsContent>

        <TabsContent value="all">
          <SectionCard title="All appointments" description="Across every date and department.">
            <Diary rows={appointments} />
          </SectionCard>
        </TabsContent>
      </Tabs>

      <Dialog open={bookOpen} onOpenChange={setBookOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Book an appointment</DialogTitle>
            <DialogDescription>
              The slot is checked against the doctor's diary — an overlapping booking is refused.
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={book} className="space-y-4">
            <Field label="Patient" required>
              <Select value={draft.patientId} onValueChange={(v) => setDraft((d) => ({ ...d, patientId: v }))}>
                <SelectTrigger>
                  <SelectValue placeholder={patients.length ? 'Select a patient' : 'Loading patients…'} />
                </SelectTrigger>
                <SelectContent>
                  {patients.map((p) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.name} — {p.id}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </Field>

            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Doctor" required>
                <Select value={draft.doctorId} onValueChange={(v) => setDraft((d) => ({ ...d, doctorId: v }))}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a doctor" />
                  </SelectTrigger>
                  <SelectContent>
                    {doctors.map((d) => (
                      <SelectItem key={d.id} value={d.id}>
                        {d.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>
              <Field label="Appointment type">
                <Select
                  value={draft.type}
                  onValueChange={(v) => setDraft((d) => ({ ...d, type: v as AppointmentType }))}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {APPOINTMENT_TYPES.map((t) => (
                      <SelectItem key={t} value={t}>
                        {t}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>
              <Field label="Date" htmlFor="apt-date">
                <Input
                  id="apt-date"
                  type="date"
                  value={draft.date}
                  onChange={(e) => setDraft((d) => ({ ...d, date: e.target.value }))}
                />
              </Field>
              <Field label="Time" htmlFor="apt-time">
                <Input
                  id="apt-time"
                  type="time"
                  value={draft.time}
                  onChange={(e) => setDraft((d) => ({ ...d, time: e.target.value }))}
                />
              </Field>
            </div>

            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setBookOpen(false)}>
                Cancel
              </Button>
              <Button type="submit" disabled={booking}>
                {booking ? 'Booking…' : 'Book appointment'}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </>
  )
}
