"""create initial HMS schema

Revision ID: fc6bbdddeeb5
Revises: c390e79190ef
Create Date: 2026-08-24 16:24:51.330197
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fc6bbdddeeb5'
down_revision: str | None = 'c390e79190ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Every PostgreSQL ENUM type this migration creates. op.drop_table() does not
#: drop types, so downgrade must remove them explicitly — otherwise a later
#: upgrade fails with 'type already exists'.
ENUM_TYPES = (
    "admission_status",
    "appointment_status",
    "appointment_type",
    "attendance_status",
    "audit_category",
    "bed_status",
    "bed_type",
    "department_type",
    "document_type",
    "expense_category",
    "expense_status",
    "gender",
    "invoice_department",
    "invoice_status",
    "lab_flag",
    "medical_history_type",
    "milestone_status",
    "notification_icon",
    "notification_severity",
    "nursing_task_type",
    "patient_status",
    "payment_method",
    "payment_status",
    "permission_group",
    "prescription_priority",
    "prescription_status",
    "rehab_plan_status",
    "rehab_trend",
    "task_priority",
    "therapy_session_status",
    "therapy_type",
    "user_role",
    "user_status",
)


# ---------------------------------------------------------------------------
# Required / optional PostgreSQL extensions
# ---------------------------------------------------------------------------

#: Required. The appointment overlap guards are GiST exclusion constraints that
#: compare uuid columns with "=", and uuid has no default GiST operator class
#: without btree_gist.
REQUIRED_EXTENSIONS = ("btree_gist",)

#: Optional. Enables a trigram index for fuzzy patient-name search. Without it
#: the schema is still complete; search falls back to prefix/ILIKE matching on
#: the btree indexes.
OPTIONAL_EXTENSIONS = ("pg_trgm",)


def _extension_available(bind, name: str) -> bool:
    return bind.execute(
        sa.text("SELECT 1 FROM pg_available_extensions WHERE name = :n"), {"n": name}
    ).scalar() is not None


def _ensure_extensions() -> set[str]:
    """Create extensions, failing loudly if a required one is missing.

    Returns the set of extension names that are actually installed.
    """
    bind = op.get_bind()
    installed: set[str] = set()

    for name in REQUIRED_EXTENSIONS:
        if not _extension_available(bind, name):
            raise RuntimeError(
                f"PostgreSQL extension {name!r} is required but not available on this server. "
                "It ships with the standard postgresql-contrib package. Install it, then re-run "
                "'alembic upgrade head'."
            )
        op.execute(f"CREATE EXTENSION IF NOT EXISTS {name}")
        installed.add(name)

    for name in OPTIONAL_EXTENSIONS:
        if _extension_available(bind, name):
            op.execute(f"CREATE EXTENSION IF NOT EXISTS {name}")
            installed.add(name)

    return installed


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    installed_extensions = _ensure_extensions()

    op.create_table('branches',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('licensed_beds', sa.Integer(), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('name', name=op.f('uq_branches_name'))
    )
    op.create_table('exercise_library',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('PHYSIOTHERAPY', 'OCCUPATIONAL_THERAPY', 'SPEECH_THERAPY', 'NEURO_REHABILITATION', 'PHYSICAL_REHABILITATION', 'HYDROTHERAPY', 'CARDIAC_REHABILITATION', name='therapy_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('default_duration', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_library')),
    sa.UniqueConstraint('category', 'name', name='uq_exercise_library_category_name')
    )
    op.create_table('medicines',
    sa.Column('medicine_number', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('rack_location', sa.String(length=60), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reorder_level >= 0', name=op.f('ck_medicines_reorder_level_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicines')),
    sa.UniqueConstraint('name', name=op.f('uq_medicines_name'))
    )
    op.create_index('ix_medicines_category', 'medicines', ['category'], unique=False)
    op.create_index('ix_medicines_is_active', 'medicines', ['is_active'], unique=False)
    op.create_index(op.f('ix_medicines_medicine_number'), 'medicines', ['medicine_number'], unique=True)
    op.create_table('permissions',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('group', sa.Enum('PATIENTS', 'SCHEDULING', 'CLINICAL', 'REHAB', 'PHARMACY', 'FINANCE', 'OPERATIONS', 'SYSTEM', name='permission_group'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=True)
    op.create_table('consultation_fees',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('appointment_type', sa.Enum('NEW_CONSULTATION', 'FOLLOW_UP', 'THERAPY_REVIEW', 'POST_OP_REVIEW', 'ASSESSMENT', 'WALK_IN', name='appointment_type'), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_consultation_fees_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_fees')),
    sa.UniqueConstraint('branch_id', 'appointment_type', name='uq_consultation_fees_branch_type')
    )
    op.create_index(op.f('ix_consultation_fees_branch_id'), 'consultation_fees', ['branch_id'], unique=False)
    op.create_table('departments',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('CLINICAL', 'THERAPY', 'SUPPORT', name='department_type'), nullable=False),
    sa.Column('head_user_id', sa.UUID(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('staff_count', sa.Integer(), nullable=False),
    sa.Column('monthly_revenue', sa.Numeric(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('utilisation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_departments_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('branch_id', 'name', name='uq_departments_branch_name')
    )
    op.create_index(op.f('ix_departments_branch_id'), 'departments', ['branch_id'], unique=False)
    op.create_table('medicine_batches',
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('purchase_price >= 0', name=op.f('ck_medicine_batches_purchase_price_non_negative')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_medicine_batches_quantity_non_negative')),
    sa.CheckConstraint('selling_price >= 0', name=op.f('ck_medicine_batches_selling_price_non_negative')),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_medicine_batches_medicine_id_medicines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_batches')),
    sa.UniqueConstraint('medicine_id', 'batch_number', name='uq_medicine_batches_medicine_batch')
    )
    op.create_index('ix_medicine_batches_expiry_date', 'medicine_batches', ['expiry_date'], unique=False)
    op.create_index('ix_medicine_batches_medicine_id', 'medicine_batches', ['medicine_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role', sa.Enum('owner', 'admin', 'doctor', 'therapist', 'nurse', 'pharmacist', 'receptionist', 'accountant', name='user_role'), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index('ix_role_permissions_role', 'role_permissions', ['role'], unique=False)
    op.create_table('wards',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_wards_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wards')),
    sa.UniqueConstraint('branch_id', 'name', name='uq_wards_branch_name')
    )
    op.create_index(op.f('ix_wards_branch_id'), 'wards', ['branch_id'], unique=False)
    op.create_table('users',
    sa.Column('user_number', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'doctor', 'therapist', 'nurse', 'pharmacist', 'receptionist', 'accountant', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'pending', name='user_status'), nullable=False),
    sa.Column('designation', sa.String(length=160), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('avatar_color', sa.String(length=80), nullable=True),
    sa.Column('initials', sa.String(length=4), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_users_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_branch_id', 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_user_number'), 'users', ['user_number'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('AUTH', 'STAFF', 'PATIENT', 'PHARMACY', 'BILLING', 'SYSTEM', name='audit_category'), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_category', 'audit_logs', ['category'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('expense_number', sa.String(length=16), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('SALARIES', 'PHARMACY_PURCHASE', 'EQUIPMENT', 'UTILITIES', 'MAINTENANCE', 'MARKETING', 'UNCATEGORISED', name='expense_category'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'INSURANCE', name='payment_method'), nullable=True),
    sa.Column('status', sa.Enum('RECORDED', 'PENDING_CATEGORISATION', 'APPROVED', name='expense_status'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_expenses_amount_non_negative')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_expenses_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_expenses_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_expenses_recorded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_branch_id', 'expenses', ['branch_id'], unique=False)
    op.create_index('ix_expenses_category', 'expenses', ['category'], unique=False)
    op.create_index('ix_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_expense_number'), 'expenses', ['expense_number'], unique=True)
    op.create_index('ix_expenses_status', 'expenses', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('icon', sa.Enum('CLINICAL', 'STOCK', 'FINANCE', 'THERAPY', 'SYSTEM', 'PATIENT', name='notification_icon'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', 'SUCCESS', name='notification_severity'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_read', 'notifications', ['read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_table('patients',
    sa.Column('patient_number', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE_OPD', 'ADMITTED_IPD', 'IN_REHABILITATION', 'DISCHARGE_PENDING', 'DISCHARGED', 'FOLLOW_UP', name='patient_status'), nullable=False),
    sa.Column('primary_condition', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('last_visit_at', sa.Date(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('assigned_doctor_id', sa.UUID(), nullable=True),
    sa.Column('assigned_therapist_id', sa.UUID(), nullable=True),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insurance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avatar_color', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['users.id'], name=op.f('fk_patients_assigned_doctor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_therapist_id'], ['users.id'], name=op.f('fk_patients_assigned_therapist_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_patients_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_patients_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index('ix_patients_assigned_doctor_id', 'patients', ['assigned_doctor_id'], unique=False)
    op.create_index('ix_patients_assigned_therapist_id', 'patients', ['assigned_therapist_id'], unique=False)
    op.create_index('ix_patients_branch_id', 'patients', ['branch_id'], unique=False)
    op.create_index(op.f('ix_patients_patient_number'), 'patients', ['patient_number'], unique=True)
    op.create_index('ix_patients_phone', 'patients', ['phone'], unique=False)
    op.create_index('ix_patients_status', 'patients', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_settings_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('branch_id', 'key', name='uq_settings_branch_key')
    )
    op.create_index(op.f('ix_settings_branch_id'), 'settings', ['branch_id'], unique=False)
    op.create_table('appointments',
    sa.Column('appointment_number', sa.String(length=16), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('therapist_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('appointment_type', sa.Enum('NEW_CONSULTATION', 'FOLLOW_UP', 'THERAPY_REVIEW', 'POST_OP_REVIEW', 'ASSESSMENT', 'WALK_IN', name='appointment_type'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'FOLLOW_UP', 'CANCELLED', 'NO_SHOW', name='appointment_status'), nullable=False),
    sa.Column('token_number', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('room', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.literal_column('doctor_id'), '='), (sa.literal_column('tsrange((appointment_date + start_time), (appointment_date + end_time))'), '&&'), where=sa.text("status NOT IN ('CANCELLED', 'NO_SHOW') AND doctor_id IS NOT NULL"), using='gist', name='ex_appointments_doctor_no_overlap'),
    postgresql.ExcludeConstraint((sa.literal_column('therapist_id'), '='), (sa.literal_column('tsrange((appointment_date + start_time), (appointment_date + end_time))'), '&&'), where=sa.text("status NOT IN ('CANCELLED', 'NO_SHOW') AND therapist_id IS NOT NULL"), using='gist', name='ex_appointments_therapist_no_overlap'),
    sa.CheckConstraint('doctor_id IS NOT NULL OR therapist_id IS NOT NULL', name=op.f('ck_appointments_clinician_required')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_appointments_end_after_start')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_appointments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_appointments_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_appointments_doctor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_appointments_therapist_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index('ix_appointments_appointment_date', 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=True)
    op.create_index('ix_appointments_doctor_date', 'appointments', ['doctor_id', 'appointment_date'], unique=False)
    op.create_index('ix_appointments_doctor_id', 'appointments', ['doctor_id'], unique=False)
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_therapist_id', 'appointments', ['therapist_id'], unique=False)
    op.create_table('beds',
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('room', sa.String(length=40), nullable=True),
    sa.Column('bed_number', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Enum('GENERAL', 'SEMI_PRIVATE', 'PRIVATE', 'ICU', 'REHAB_SUITE', name='bed_type'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'CLEANING', name='bed_status'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('reserved_for', sa.String(length=160), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_beds_patient_id_patients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], name=op.f('fk_beds_ward_id_wards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beds')),
    sa.UniqueConstraint('ward_id', 'bed_number', name='uq_beds_ward_bed_number')
    )
    op.create_index('ix_beds_status', 'beds', ['status'], unique=False)
    op.create_index('ix_beds_ward_id', 'beds', ['ward_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=24), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.Enum('OPD', 'IPD', 'PHARMACY', 'THERAPY', 'DIAGNOSTICS', name='invoice_department'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'PARTIALLY_PAID', 'UNPAID', 'OVERDUE', name='invoice_status'), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount >= 0', name=op.f('ck_invoices_discount_non_negative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_invoices_subtotal_non_negative')),
    sa.CheckConstraint('tax >= 0', name=op.f('ck_invoices_tax_non_negative')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_invoices_total_non_negative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_invoices_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invoices_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_invoices_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index('ix_invoices_branch_id', 'invoices', ['branch_id'], unique=False)
    op.create_index('ix_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_patient_id', 'invoices', ['patient_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('lab_results',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('test', sa.String(length=200), nullable=False),
    sa.Column('reported_on', sa.Date(), nullable=False),
    sa.Column('flag', sa.Enum('NORMAL', 'ABNORMAL', 'CRITICAL', name='lab_flag'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_lab_results_doctor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_lab_results_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_lab_results_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_results'))
    )
    op.create_index('ix_lab_results_patient_id', 'lab_results', ['patient_id'], unique=False)
    op.create_index('ix_lab_results_reported_on', 'lab_results', ['reported_on'], unique=False)
    op.create_index('ix_lab_results_reviewed', 'lab_results', ['reviewed'], unique=False)
    op.create_table('medical_history_entries',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('DIAGNOSIS', 'SURGERY', 'INJURY', 'ALLERGY', 'CHRONIC_CONDITION', 'LAB_RESULT', name='medical_history_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('clinician_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], name=op.f('fk_medical_history_entries_clinician_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medical_history_entries_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_history_entries'))
    )
    op.create_index('ix_medical_history_patient_date', 'medical_history_entries', ['patient_id', 'entry_date'], unique=False)
    op.create_table('patient_documents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('REPORT', 'SCAN', 'CONSENT', 'INSURANCE', 'DISCHARGE_SUMMARY', name='document_type'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('uploaded_on', sa.Date(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_documents_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_patient_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_documents'))
    )
    op.create_index('ix_patient_documents_patient_id', 'patient_documents', ['patient_id'], unique=False)
    op.create_table('rehab_plans',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('modalities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='rehab_plan_status'), nullable=False),
    sa.Column('completed_sessions', sa.Integer(), nullable=False),
    sa.Column('attendance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('adherence_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trend', sa.Enum('ON_TRACK', 'AHEAD_OF_PLAN', 'PLATEAUED', 'AT_RISK', 'COMPLETED', name='rehab_trend'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_sessions >= 0 AND completed_sessions <= total_sessions', name=op.f('ck_rehab_plans_completed_within_total')),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_rehab_plans_end_after_start')),
    sa.CheckConstraint('total_sessions > 0', name=op.f('ck_rehab_plans_total_sessions_positive')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_rehab_plans_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_rehab_plans_therapist_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rehab_plans'))
    )
    op.create_index('ix_rehab_plans_patient_id', 'rehab_plans', ['patient_id'], unique=False)
    op.create_index('ix_rehab_plans_status', 'rehab_plans', ['status'], unique=False)
    op.create_index('ix_rehab_plans_therapist_id', 'rehab_plans', ['therapist_id'], unique=False)
    op.create_table('admissions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('bed_id', sa.UUID(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('expected_discharge', sa.Date(), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ADMITTED', 'DISCHARGE_PENDING', 'DISCHARGED', name='admission_status'), nullable=False),
    sa.Column('admitted_by', sa.UUID(), nullable=True),
    sa.Column('attending_doctor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admitted_by'], ['users.id'], name=op.f('fk_admissions_admitted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attending_doctor_id'], ['users.id'], name=op.f('fk_admissions_attending_doctor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], name=op.f('fk_admissions_bed_id_beds'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_admissions_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admissions'))
    )
    op.create_index('ix_admissions_patient_id', 'admissions', ['patient_id'], unique=False)
    op.create_index('ix_admissions_status', 'admissions', ['status'], unique=False)
    op.create_index('uq_admissions_active_bed', 'admissions', ['bed_id'], unique=True, postgresql_where=sa.text("status = 'ADMITTED'"))
    op.create_index('uq_admissions_active_patient', 'admissions', ['patient_id'], unique=True, postgresql_where=sa.text("status = 'ADMITTED'"))
    op.create_table('consultations',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('examination_notes', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('care_plan', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_consultations_appointment_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_consultations_doctor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_consultations_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations'))
    )
    op.create_index('ix_consultations_doctor_id', 'consultations', ['doctor_id'], unique=False)
    op.create_index('ix_consultations_patient_created', 'consultations', ['patient_id', 'created_at'], unique=False)
    op.create_index('ix_consultations_patient_id', 'consultations', ['patient_id'], unique=False)
    op.create_index('uq_consultations_appointment_id', 'consultations', ['appointment_id'], unique=True, postgresql_where=sa.text('appointment_id IS NOT NULL'))
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_invoice_items_amount_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_invoice_items_quantity_positive')),
    sa.CheckConstraint('rate >= 0', name=op.f('ck_invoice_items_rate_non_negative')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    op.create_index('ix_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('lab_result_values',
    sa.Column('lab_result_id', sa.UUID(), nullable=False),
    sa.Column('analyte', sa.String(length=160), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('reference_range', sa.String(length=80), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_result_id'], ['lab_results.id'], name=op.f('fk_lab_result_values_lab_result_id_lab_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_result_values'))
    )
    op.create_index('ix_lab_result_values_result_id', 'lab_result_values', ['lab_result_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_number', sa.String(length=16), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'INSURANCE', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('SETTLED', 'PROCESSING', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=120), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name=op.f('fk_payments_collected_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_paid_at', 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=True)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('rehab_milestones',
    sa.Column('rehab_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACHIEVED', 'MISSED', name='milestone_status'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rehab_plan_id'], ['rehab_plans.id'], name=op.f('fk_rehab_milestones_rehab_plan_id_rehab_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rehab_milestones'))
    )
    op.create_index('ix_rehab_milestones_plan_id', 'rehab_milestones', ['rehab_plan_id'], unique=False)
    op.create_table('rehab_progress_points',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('rehab_plan_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_label', sa.String(length=16), nullable=True),
    sa.Column('pain', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('mobility', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('adherence', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('adherence IS NULL OR adherence BETWEEN 0 AND 100', name=op.f('ck_rehab_progress_points_adherence_range')),
    sa.CheckConstraint('mobility IS NULL OR mobility BETWEEN 0 AND 100', name=op.f('ck_rehab_progress_points_mobility_range')),
    sa.CheckConstraint('pain IS NULL OR pain BETWEEN 0 AND 10', name=op.f('ck_rehab_progress_points_pain_range')),
    sa.CheckConstraint('strength IS NULL OR strength BETWEEN 0 AND 100', name=op.f('ck_rehab_progress_points_strength_range')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_rehab_progress_points_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rehab_plan_id'], ['rehab_plans.id'], name=op.f('fk_rehab_progress_points_rehab_plan_id_rehab_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rehab_progress_points')),
    sa.UniqueConstraint('rehab_plan_id', 'week_start', name='uq_rehab_progress_plan_week')
    )
    op.create_index('ix_rehab_progress_patient_recorded', 'rehab_progress_points', ['patient_id', 'recorded_at'], unique=False)
    op.create_table('therapy_sessions',
    sa.Column('session_number', sa.String(length=16), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=True),
    sa.Column('rehab_plan_id', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.Enum('PHYSIOTHERAPY', 'OCCUPATIONAL_THERAPY', 'SPEECH_THERAPY', 'NEURO_REHABILITATION', 'PHYSICAL_REHABILITATION', 'HYDROTHERAPY', 'CARDIAC_REHABILITATION', name='therapy_type'), nullable=False),
    sa.Column('room', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'MISSED', name='therapy_session_status'), nullable=False),
    sa.Column('attendance_status', sa.Enum('ATTENDED', 'LATE', 'NO_SHOW', 'CANCELLED', name='attendance_status'), nullable=True),
    sa.Column('pain_before', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('pain_after', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('mobility_score', sa.Integer(), nullable=True),
    sa.Column('strength_score', sa.Integer(), nullable=True),
    sa.Column('therapist_notes', sa.Text(), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('next_session_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration IS NULL OR duration > 0', name=op.f('ck_therapy_sessions_duration_positive')),
    sa.CheckConstraint('mobility_score IS NULL OR mobility_score BETWEEN 0 AND 100', name=op.f('ck_therapy_sessions_mobility_range')),
    sa.CheckConstraint('pain_after IS NULL OR pain_after BETWEEN 0 AND 10', name=op.f('ck_therapy_sessions_pain_after_range')),
    sa.CheckConstraint('pain_before IS NULL OR pain_before BETWEEN 0 AND 10', name=op.f('ck_therapy_sessions_pain_before_range')),
    sa.CheckConstraint('strength_score IS NULL OR strength_score BETWEEN 0 AND 100', name=op.f('ck_therapy_sessions_strength_range')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_therapy_sessions_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rehab_plan_id'], ['rehab_plans.id'], name=op.f('fk_therapy_sessions_rehab_plan_id_rehab_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_therapy_sessions_therapist_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapy_sessions'))
    )
    op.create_index('ix_therapy_sessions_patient_id', 'therapy_sessions', ['patient_id'], unique=False)
    op.create_index('ix_therapy_sessions_plan_id', 'therapy_sessions', ['rehab_plan_id'], unique=False)
    op.create_index('ix_therapy_sessions_session_date', 'therapy_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_session_number'), 'therapy_sessions', ['session_number'], unique=True)
    op.create_index('ix_therapy_sessions_therapist_date', 'therapy_sessions', ['therapist_id', 'session_date'], unique=False)
    op.create_index('ix_therapy_sessions_therapist_id', 'therapy_sessions', ['therapist_id'], unique=False)
    op.create_table('discharge_checklist_items',
    sa.Column('admission_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_discharge_checklist_items_admission_id_admissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_discharge_checklist_items_completed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discharge_checklist_items'))
    )
    op.create_index('ix_discharge_checklist_admission_id', 'discharge_checklist_items', ['admission_id'], unique=False)
    op.create_table('nursing_tasks',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('admission_id', sa.UUID(), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('bed_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('VITALS', 'MEDICATION', 'DOCTOR_INSTRUCTION', 'CARE_TASK', 'THERAPY_PREP', name='nursing_task_type'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_label', sa.String(length=60), nullable=True),
    sa.Column('priority', sa.Enum('ROUTINE', 'HIGH', 'CRITICAL', name='task_priority'), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_nursing_tasks_admission_id_admissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_nursing_tasks_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], name=op.f('fk_nursing_tasks_bed_id_beds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_nursing_tasks_completed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_nursing_tasks_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], name=op.f('fk_nursing_tasks_ward_id_wards'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nursing_tasks'))
    )
    op.create_index('ix_nursing_tasks_assigned_to', 'nursing_tasks', ['assigned_to'], unique=False)
    op.create_index('ix_nursing_tasks_done_priority', 'nursing_tasks', ['done', 'priority'], unique=False)
    op.create_index('ix_nursing_tasks_patient_id', 'nursing_tasks', ['patient_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('prescription_number', sa.String(length=16), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_DISPENSED', 'DISPENSED', 'CANCELLED', name='prescription_status'), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', name='prescription_priority'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_prescriptions_consultation_id_consultations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_prescriptions_doctor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_prescriptions_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_index('ix_prescriptions_doctor_id', 'prescriptions', ['doctor_id'], unique=False)
    op.create_index('ix_prescriptions_patient_id', 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescription_number'), 'prescriptions', ['prescription_number'], unique=True)
    op.create_index('ix_prescriptions_status', 'prescriptions', ['status'], unique=False)
    op.create_table('therapy_session_exercises',
    sa.Column('therapy_session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('exercise_name', sa.String(length=200), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], name=op.f('fk_therapy_session_exercises_exercise_id_exercise_library'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['therapy_session_id'], ['therapy_sessions.id'], name=op.f('fk_therapy_session_exercises_therapy_session_id_therapy_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapy_session_exercises'))
    )
    op.create_index('ix_session_exercises_session_id', 'therapy_session_exercises', ['therapy_session_id'], unique=False)
    op.create_table('vitals',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('admission_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('diastolic IS NULL OR diastolic BETWEEN 20 AND 200', name=op.f('ck_vitals_diastolic_range')),
    sa.CheckConstraint('heart_rate IS NULL OR heart_rate BETWEEN 20 AND 250', name=op.f('ck_vitals_heart_rate_range')),
    sa.CheckConstraint('respiratory_rate IS NULL OR respiratory_rate BETWEEN 4 AND 80', name=op.f('ck_vitals_respiratory_rate_range')),
    sa.CheckConstraint('spo2 IS NULL OR spo2 BETWEEN 50 AND 100', name=op.f('ck_vitals_spo2_range')),
    sa.CheckConstraint('systolic IS NULL OR systolic BETWEEN 40 AND 300', name=op.f('ck_vitals_systolic_range')),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_vitals_admission_id_admissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_vitals_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_vitals_recorded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vitals'))
    )
    op.create_index('ix_vitals_patient_recorded_at', 'vitals', ['patient_id', 'recorded_at'], unique=False)
    op.create_table('prescription_items',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('strength', sa.String(length=80), nullable=True),
    sa.Column('dosage', sa.String(length=120), nullable=True),
    sa.Column('frequency', sa.String(length=120), nullable=True),
    sa.Column('duration', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_prescription_items_quantity_positive')),
    sa.CheckConstraint('quantity_dispensed <= quantity', name=op.f('ck_prescription_items_dispensed_within_prescribed')),
    sa.CheckConstraint('quantity_dispensed >= 0', name=op.f('ck_prescription_items_dispensed_non_negative')),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_prescription_items_medicine_id_medicines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_prescription_items_prescription_id_prescriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription_items'))
    )
    op.create_index('ix_prescription_items_medicine_id', 'prescription_items', ['medicine_id'], unique=False)
    op.create_index('ix_prescription_items_prescription_id', 'prescription_items', ['prescription_id'], unique=False)
    op.create_table('dispense_records',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('prescription_item_id', sa.UUID(), nullable=False),
    sa.Column('medicine_batch_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dispensed_by', sa.UUID(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_dispense_records_quantity_positive')),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], name=op.f('fk_dispense_records_dispensed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_batch_id'], ['medicine_batches.id'], name=op.f('fk_dispense_records_medicine_batch_id_medicine_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_dispense_records_prescription_id_prescriptions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_item_id'], ['prescription_items.id'], name=op.f('fk_dispense_records_prescription_item_id_prescription_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispense_records'))
    )
    op.create_index('ix_dispense_records_batch_id', 'dispense_records', ['medicine_batch_id'], unique=False)
    op.create_index('ix_dispense_records_dispensed_at', 'dispense_records', ['dispensed_at'], unique=False)
    op.create_index('ix_dispense_records_prescription_id', 'dispense_records', ['prescription_id'], unique=False)
    # departments.head_user_id <-> users.department_id is a circular reference,
    # so this FK is added after both tables exist rather than inline.
    op.create_foreign_key(
        "fk_departments_head_user_id_users",
        "departments",
        "users",
        ["head_user_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Fuzzy patient-name search. Only created when pg_trgm is installed; the
    # rest of the schema does not depend on it.
    if "pg_trgm" in installed_extensions:
        op.execute(
            "CREATE INDEX ix_patients_name_trgm ON patients "
            "USING gin ((first_name || ' ' || last_name) gin_trgm_ops)"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_patients_name_trgm")
    op.execute(
        "ALTER TABLE departments DROP CONSTRAINT IF EXISTS fk_departments_head_user_id_users"
    )

    op.drop_index('ix_dispense_records_prescription_id', table_name='dispense_records')
    op.drop_index('ix_dispense_records_dispensed_at', table_name='dispense_records')
    op.drop_index('ix_dispense_records_batch_id', table_name='dispense_records')
    op.drop_table('dispense_records')
    op.drop_index('ix_prescription_items_prescription_id', table_name='prescription_items')
    op.drop_index('ix_prescription_items_medicine_id', table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index('ix_vitals_patient_recorded_at', table_name='vitals')
    op.drop_table('vitals')
    op.drop_index('ix_session_exercises_session_id', table_name='therapy_session_exercises')
    op.drop_table('therapy_session_exercises')
    op.drop_index('ix_prescriptions_status', table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_prescription_number'), table_name='prescriptions')
    op.drop_index('ix_prescriptions_patient_id', table_name='prescriptions')
    op.drop_index('ix_prescriptions_doctor_id', table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_nursing_tasks_patient_id', table_name='nursing_tasks')
    op.drop_index('ix_nursing_tasks_done_priority', table_name='nursing_tasks')
    op.drop_index('ix_nursing_tasks_assigned_to', table_name='nursing_tasks')
    op.drop_table('nursing_tasks')
    op.drop_index('ix_discharge_checklist_admission_id', table_name='discharge_checklist_items')
    op.drop_table('discharge_checklist_items')
    op.drop_index('ix_therapy_sessions_therapist_id', table_name='therapy_sessions')
    op.drop_index('ix_therapy_sessions_therapist_date', table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_session_number'), table_name='therapy_sessions')
    op.drop_index('ix_therapy_sessions_session_date', table_name='therapy_sessions')
    op.drop_index('ix_therapy_sessions_plan_id', table_name='therapy_sessions')
    op.drop_index('ix_therapy_sessions_patient_id', table_name='therapy_sessions')
    op.drop_table('therapy_sessions')
    op.drop_index('ix_rehab_progress_patient_recorded', table_name='rehab_progress_points')
    op.drop_table('rehab_progress_points')
    op.drop_index('ix_rehab_milestones_plan_id', table_name='rehab_milestones')
    op.drop_table('rehab_milestones')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index('ix_payments_paid_at', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_lab_result_values_result_id', table_name='lab_result_values')
    op.drop_table('lab_result_values')
    op.drop_index('ix_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index('uq_consultations_appointment_id', table_name='consultations', postgresql_where=sa.text('appointment_id IS NOT NULL'))
    op.drop_index('ix_consultations_patient_id', table_name='consultations')
    op.drop_index('ix_consultations_patient_created', table_name='consultations')
    op.drop_index('ix_consultations_doctor_id', table_name='consultations')
    op.drop_table('consultations')
    op.drop_index('uq_admissions_active_patient', table_name='admissions', postgresql_where=sa.text("status = 'ADMITTED'"))
    op.drop_index('uq_admissions_active_bed', table_name='admissions', postgresql_where=sa.text("status = 'ADMITTED'"))
    op.drop_index('ix_admissions_status', table_name='admissions')
    op.drop_index('ix_admissions_patient_id', table_name='admissions')
    op.drop_table('admissions')
    op.drop_index('ix_rehab_plans_therapist_id', table_name='rehab_plans')
    op.drop_index('ix_rehab_plans_status', table_name='rehab_plans')
    op.drop_index('ix_rehab_plans_patient_id', table_name='rehab_plans')
    op.drop_table('rehab_plans')
    op.drop_index('ix_patient_documents_patient_id', table_name='patient_documents')
    op.drop_table('patient_documents')
    op.drop_index('ix_medical_history_patient_date', table_name='medical_history_entries')
    op.drop_table('medical_history_entries')
    op.drop_index('ix_lab_results_reviewed', table_name='lab_results')
    op.drop_index('ix_lab_results_reported_on', table_name='lab_results')
    op.drop_index('ix_lab_results_patient_id', table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_patient_id', table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index('ix_invoices_due_date', table_name='invoices')
    op.drop_index('ix_invoices_branch_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_beds_ward_id', table_name='beds')
    op.drop_index('ix_beds_status', table_name='beds')
    op.drop_table('beds')
    op.drop_index('ix_appointments_therapist_id', table_name='appointments')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_index('ix_appointments_doctor_id', table_name='appointments')
    op.drop_index('ix_appointments_doctor_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_index('ix_appointments_appointment_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_settings_branch_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index('ix_patients_status', table_name='patients')
    op.drop_index('ix_patients_phone', table_name='patients')
    op.drop_index(op.f('ix_patients_patient_number'), table_name='patients')
    op.drop_index('ix_patients_branch_id', table_name='patients')
    op.drop_index('ix_patients_assigned_therapist_id', table_name='patients')
    op.drop_index('ix_patients_assigned_doctor_id', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_expenses_status', table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_index('ix_expenses_expense_date', table_name='expenses')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_index('ix_expenses_branch_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_category', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_user_number'), table_name='users')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_branch_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_wards_branch_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index('ix_role_permissions_role', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_medicine_batches_medicine_id', table_name='medicine_batches')
    op.drop_index('ix_medicine_batches_expiry_date', table_name='medicine_batches')
    op.drop_table('medicine_batches')
    op.drop_index(op.f('ix_departments_branch_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_consultation_fees_branch_id'), table_name='consultation_fees')
    op.drop_table('consultation_fees')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_medicines_medicine_number'), table_name='medicines')
    op.drop_index('ix_medicines_is_active', table_name='medicines')
    op.drop_index('ix_medicines_category', table_name='medicines')
    op.drop_table('medicines')
    op.drop_table('exercise_library')
    op.drop_table('branches')
    # ### end Alembic commands ###

    # Enum types outlive their tables, so remove them explicitly.
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
