"""therapy session sequence within plan

Revision ID: 4101a06977ac
Revises: b3c449578759
Create Date: 2026-08-24 21:43:50.187379
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4101a06977ac'
down_revision: str | None = 'b3c449578759'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapy_sessions', sa.Column('sequence_in_plan', sa.Integer(), nullable=True))
    op.create_index('uq_therapy_sessions_plan_sequence', 'therapy_sessions', ['rehab_plan_id', 'sequence_in_plan'], unique=True, postgresql_where=sa.text('rehab_plan_id IS NOT NULL AND sequence_in_plan IS NOT NULL'))
    op.create_check_constraint(op.f('ck_therapy_sessions_sequence_positive'), 'therapy_sessions', 'sequence_in_plan IS NULL OR sequence_in_plan > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_therapy_sessions_sequence_positive'), 'therapy_sessions', type_='check')
    op.drop_index('uq_therapy_sessions_plan_sequence', table_name='therapy_sessions', postgresql_where=sa.text('rehab_plan_id IS NOT NULL AND sequence_in_plan IS NOT NULL'))
    op.drop_column('therapy_sessions', 'sequence_in_plan')
    # ### end Alembic commands ###
