"""AI guardrails: usage metrics and approval records

Additive only. Five nullable columns on ``ai_audit_logs`` for what a run
consumed and which code version produced it, and one new table recording the
human decisions behind AI-proposed actions.

``ai_agent_type`` already exists from the previous revision, so it is reused
with ``create_type=False``. Letting autogenerate emit a bare ``sa.Enum`` here
would make this migration fail on any database that has already run the last
one, which is every database that matters.

Revision ID: f287d24670a4
Revises: 96827d106f6b
Create Date: 2026-08-27 15:53:42.153069
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'f287d24670a4'
down_revision: str | None = '96827d106f6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_approvals',
    sa.Column(
        'agent_type',
        postgresql.ENUM(
            'PATIENT_RECAP', 'CLINICAL_DOCUMENTATION', 'BILLING_ACCURACY',
            'FOLLOW_UP', 'FINANCE_INSIGHTS',
            name='ai_agent_type', create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('audit_log_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('applied_type', sa.String(length=80), nullable=True),
    sa.Column('applied_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['ai_audit_logs.id'], name=op.f('fk_ai_approvals_audit_log_id_ai_audit_logs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_approvals_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_approvals'))
    )
    op.create_index('ix_ai_approvals_agent', 'ai_approvals', ['agent_type'], unique=False)
    op.create_index('ix_ai_approvals_created_at', 'ai_approvals', ['created_at'], unique=False)
    op.create_index('ix_ai_approvals_entity', 'ai_approvals', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_ai_approvals_user_id', 'ai_approvals', ['user_id'], unique=False)
    op.add_column('ai_audit_logs', sa.Column('agent_version', sa.String(length=60), nullable=True))
    op.add_column('ai_audit_logs', sa.Column('retries', sa.Integer(), nullable=True))
    op.add_column('ai_audit_logs', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_audit_logs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_audit_logs', sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_audit_logs', 'estimated_cost')
    op.drop_column('ai_audit_logs', 'output_tokens')
    op.drop_column('ai_audit_logs', 'input_tokens')
    op.drop_column('ai_audit_logs', 'retries')
    op.drop_column('ai_audit_logs', 'agent_version')
    op.drop_index('ix_ai_approvals_user_id', table_name='ai_approvals')
    op.drop_index('ix_ai_approvals_entity', table_name='ai_approvals')
    op.drop_index('ix_ai_approvals_created_at', table_name='ai_approvals')
    op.drop_index('ix_ai_approvals_agent', table_name='ai_approvals')
    op.drop_table('ai_approvals')
    # ### end Alembic commands ###
