"""pharmacy point of sale

Revision ID: 1ade4b39a11d
Revises: 4101a06977ac
Create Date: 2026-08-24 22:41:41.748239
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '1ade4b39a11d'
down_revision: str | None = '4101a06977ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_sales',
    sa.Column('sale_number', sa.String(length=16), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=160), nullable=True),
    sa.Column('sold_by', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    # The payment_method type already exists — invoices and payments have used
    # it since the baseline schema. create_type=False reuses it instead of
    # failing on a duplicate CREATE TYPE.
    sa.Column(
        'payment_method',
        postgresql.ENUM(
            'CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'INSURANCE',
            name='payment_method', create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount >= 0', name=op.f('ck_pharmacy_sales_discount_non_negative')),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name=op.f('ck_pharmacy_sales_discount_percent_range')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_pharmacy_sales_subtotal_non_negative')),
    sa.CheckConstraint('tax >= 0', name=op.f('ck_pharmacy_sales_tax_non_negative')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_pharmacy_sales_total_non_negative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_pharmacy_sales_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_pharmacy_sales_patient_id_patients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sold_by'], ['users.id'], name=op.f('fk_pharmacy_sales_sold_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacy_sales'))
    )
    op.create_index('ix_pharmacy_sales_created_at', 'pharmacy_sales', ['created_at'], unique=False)
    op.create_index('ix_pharmacy_sales_patient_id', 'pharmacy_sales', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_sales_sale_number'), 'pharmacy_sales', ['sale_number'], unique=True)
    op.create_table('pharmacy_sale_items',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('medicine_batch_id', sa.UUID(), nullable=True),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_pharmacy_sale_items_line_total_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_pharmacy_sale_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_pharmacy_sale_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['medicine_batch_id'], ['medicine_batches.id'], name=op.f('fk_pharmacy_sale_items_medicine_batch_id_medicine_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_pharmacy_sale_items_medicine_id_medicines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy_sales.id'], name=op.f('fk_pharmacy_sale_items_sale_id_pharmacy_sales'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacy_sale_items'))
    )
    op.create_index('ix_pharmacy_sale_items_batch_id', 'pharmacy_sale_items', ['medicine_batch_id'], unique=False)
    op.create_index('ix_pharmacy_sale_items_sale_id', 'pharmacy_sale_items', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # payment_method is left in place: it is shared with invoices and payments.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pharmacy_sale_items_sale_id', table_name='pharmacy_sale_items')
    op.drop_index('ix_pharmacy_sale_items_batch_id', table_name='pharmacy_sale_items')
    op.drop_table('pharmacy_sale_items')
    op.drop_index(op.f('ix_pharmacy_sales_sale_number'), table_name='pharmacy_sales')
    op.drop_index('ix_pharmacy_sales_patient_id', table_name='pharmacy_sales')
    op.drop_index('ix_pharmacy_sales_created_at', table_name='pharmacy_sales')
    op.drop_table('pharmacy_sales')
    # ### end Alembic commands ###
