"""AI intelligence layer: run history, staged documents, message drafts

Three tables, none of which any existing feature reads. The AI layer is
additive by design, so downgrading removes it without touching a clinical or
financial row.

Plus one column on ``patients``: ``contact_consent``. It defaults to false
because the reminder queue must not read a stored phone number as permission to
use it, and a column that defaults to true would do exactly that for every
patient already on file.

Revision ID: 96827d106f6b
Revises: c7a1e2f9b4d3
Create Date: 2026-08-27 12:53:50.137825
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '96827d106f6b'
down_revision: str | None = 'c7a1e2f9b4d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: The enum types this migration creates. op.drop_table() leaves types behind,
#: so downgrade has to remove them explicitly or the next upgrade fails with
#: "type already exists".
ENUM_TYPES = (
    "ai_agent_type",
    "ai_review_status",
    "ai_run_status",
    "document_kind",
    "message_channel",
    "message_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Enum('PATIENT_RECAP', 'CLINICAL_DOCUMENTATION', 'BILLING_ACCURACY', 'FOLLOW_UP', 'FINANCE_INSIGHTS', name='ai_agent_type'), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('prompt_version', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('SUCCEEDED', 'DEGRADED', 'INVALID_OUTPUT', 'FAILED', 'RATE_LIMITED', name='ai_run_status'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('completion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_audit_logs'))
    )
    op.create_index('ix_ai_audit_logs_agent', 'ai_audit_logs', ['agent_type'], unique=False)
    op.create_index('ix_ai_audit_logs_created_at', 'ai_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_ai_audit_logs_entity', 'ai_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_ai_audit_logs_request_id', 'ai_audit_logs', ['request_id'], unique=False)
    op.create_index('ix_ai_audit_logs_user_id', 'ai_audit_logs', ['user_id'], unique=False)
    op.create_table('ai_documents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('PRESCRIPTION', 'DOCTOR_NOTE', 'DISCHARGE_NOTE', 'REFERRAL', 'LAB_DOCUMENT', 'THERAPY_NOTE', 'UNKNOWN', name='document_kind'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_provider', sa.String(length=60), nullable=True),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='ai_review_status'), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_type', sa.String(length=80), nullable=True),
    sa.Column('applied_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ai_documents_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_ai_documents_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_ai_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_documents'))
    )
    op.create_index('ix_ai_documents_patient_id', 'ai_documents', ['patient_id'], unique=False)
    op.create_index('ix_ai_documents_status', 'ai_documents', ['review_status'], unique=False)
    op.create_index('ix_ai_documents_uploaded_by', 'ai_documents', ['uploaded_by'], unique=False)
    op.create_table('message_drafts',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', name='message_channel'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('due_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'SENT', 'DELIVERED', 'REJECTED', 'FAILED', name='message_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_message_drafts_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_message_drafts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_message_drafts_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_drafts'))
    )
    op.create_index('ix_message_drafts_due', 'message_drafts', ['due_on'], unique=False)
    op.create_index('ix_message_drafts_patient_id', 'message_drafts', ['patient_id'], unique=False)
    op.create_index('ix_message_drafts_status', 'message_drafts', ['status'], unique=False)
    op.add_column(
        'patients',
        sa.Column(
            'contact_consent',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'contact_consent')
    op.drop_index('ix_message_drafts_status', table_name='message_drafts')
    op.drop_index('ix_message_drafts_patient_id', table_name='message_drafts')
    op.drop_index('ix_message_drafts_due', table_name='message_drafts')
    op.drop_table('message_drafts')
    op.drop_index('ix_ai_documents_uploaded_by', table_name='ai_documents')
    op.drop_index('ix_ai_documents_status', table_name='ai_documents')
    op.drop_index('ix_ai_documents_patient_id', table_name='ai_documents')
    op.drop_table('ai_documents')
    op.drop_index('ix_ai_audit_logs_user_id', table_name='ai_audit_logs')
    op.drop_index('ix_ai_audit_logs_request_id', table_name='ai_audit_logs')
    op.drop_index('ix_ai_audit_logs_entity', table_name='ai_audit_logs')
    op.drop_index('ix_ai_audit_logs_created_at', table_name='ai_audit_logs')
    op.drop_index('ix_ai_audit_logs_agent', table_name='ai_audit_logs')
    op.drop_table('ai_audit_logs')
    # ### end Alembic commands ###

    # Enum types outlive their tables, so remove them explicitly.
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
